defaults:
  - dataset: UKB
  - model: ft_transformer
  - optimizer: adamw
  - training: default

pretrained_model: ./results/DL_based/FTTransformer_ep_100_bs_256
save_path: ./results/DL_based/FTTransformer_ep_100_bs_256/${dataset.variable_type}/Interpret

gpu: 3
test: true

n_fold: 5
n_iterations: 5

wandb: true
project: UKB_interpret
